service: demesne-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-4'}
  environment:
    NODE_ENV: ${self:provider.stage}
    PORT: 3001

functions:
  spells:
    handler: dist/index.spellHandler
    events:
      - http:
          path: /api/spells
          method: get
          cors: true

  creatures:
    handler: dist/index.creatureHandler
    events:
      - http:
          path: /api/creatures
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3001
    lambdaPort: 3002
    noPrependStageInUrl: true 